modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="elementiummod"
version="1.0.0"
displayName="Elementium Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="sruly09"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.elementiummod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



